name: CI â€“ macOS

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Bazelisk (the recommended Bazel launcher)
      - name: Install Bazelisk
        run: brew install bazelisk

      # Install Doxygen, to generate documentation
      - name: Install Doxygen
        run: brew install doxygen

      # Install clang 20
      - name: Install Clang
        run: brew install llvm@20

      # Softlink llvm@20 to llvm
      - name: Softlink Clang
        run: ln -s /opt/homebrew/opt/llvm@20 /opt/homebrew/opt/llvm

      # Build everything
      - name: Build all targets
        run: bazelisk build //...

      # Run all tests
      - name: Run all tests
        run: bazelisk test //...
